using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheCorebanking.Finance.Services
{
    public enum PostType
    {
        ACCOUNT = 1,
        SINGLETRANSFER = 2,
        CASHWITHDRAWAL = 3,
        INTERESTSUSPENSION = 4,
        LOANTERMINATION = 5,
        LOANCANCELATION = 6,
        CASHDEPOSIT = 7,
        LOANRESTRUCTURE = 8,
        PETTYCASH = 9,
        FREEZEACCOUNT = 10,
        LOANWALKOUT = 11,
        DETAILS = 12,
        MANDATE = 13,
        REFEREE = 14,
        FEE = 15,
        COLLATERAL = 16,
        ACTIVATE = 17,
        STAFF = 18,
        OPERATINGEXPENSE = 19,
        STANDINGORDER = 20,
        SWEEP = 21,
        COMPANY = 22,
        PAYMENT = 23,
        MMARKET = 24,
        PREPAYMENT = 25,
        PLACEMENTOVERRIDE = 26,
        TIEROVERRIDE = 27,
        MRATEREVISION = 28,
        MCANCELLATION = 29,
        MPARTIALLIQUIDATION = 30,
        MMARKETADDITION = 31,
        MMARKETROLLOVER = 32,
        MARKETMATURITY = 33,
        MMARKETLIQUIDATION = 34,
        MMARKETREDISCOUNTING = 35,
        CHEQUECLEARING = 36,
        CHEQUEREGISTRY = 37,
        BONDBUY = 38,
        BONDSELL = 39,
        CUSTOMER = 40,
        MMARKETTENORREVISION = 41,
        JOURNAL = 42,
        DRAFT = 43,
        CHEQUEBOOK = 44,
        FUNDCHEQUE = 45,
        LOANDISBURSEMENT = 46,
        DEALLETTER = 47,
        LETTERS = 48,
        BIDDING = 49,
        CASAACCOUNT = 50,
        MMARKETCCOUNTTRANSFER = 51,
        BONDBIDDING = 52,
        TBBIDDING = 53,
        OVERDRAFT = 54,
        PNCPND = 55,
        MMARKETCREATION = 56,
        COT = 57,
        CASAREVERSAL = 58,
        REVERSEFREEZE = 59,
        CHANGEACCOUNT = 60,
        CHANGEINRATE = 61,
        REVERSAL = 62,
        PRINCIPALADDITION = 63,
        PRINCIPALREDUCTION = 64,
        TELLERSJOURNAL = 65,
        FALSECHEQUECLEARING = 66,
        STOPCHEQUE = 67,
        CHEQUEREQUEST = 68,
        DEFAULTACCOUNT = 69,
        SYSCONBACKDATEAPPROVAL = 70,
        ADJUSTSCHEDULE = 71,
        ACCOUNTSENSITIVITY = 72,
        GENERALUPLOAD = 73,
        AUDITMEMO = 74,
        CHANGEREPAYMENTDATE = 75,
        JOURNALREVERSAL = 76,
        LOANREVERSAL = 77,
        MMARKETREVERSAL = 78,
        BRANCHCREATION = 79,
        DEPARTMENTCREATION = 80,
        MAPDEPARTMENTTOBRANCH = 81,
        CREATECOLLATERAL = 82,
        CREATEAPPROVINGOFFICER = 83,
        STAMPDUTY = 84,
        LOANWRITEOFF = 85,
        CREDITAUTHORIZATION = 86,
        MULTIPLETRANSFER = 87,
        BULKTRANSFER = 88,
        CHQDEPOSIT = 89,
        CHQWITHDRAWAL = 90,
        VAULTIN = 91,
        VAULTOUT = 92,
        CLOSEACCOUNT = 93,


    }
}
