using System;
using System.Collections.Generic;
using System.Text;

namespace TheCorebanking.Finance.Data
{
   public enum OperationModel
    {
        accounttype,
        accountcategory,
        currency,
        chartofaccount
    }

    public enum Operations {
        ACCOUNT = 1,
    TRANSFER = 2,
    WITHDRAWAL = 3,
    REVISION = 4,
    SUSPENSION = 5,
    TERMINATION = 6,
    CANCELATION = 7,
    DEPOSIT = 8,
    RESTRUCTURE = 9,
    CLOSE = 10,
    FREEZE = 11,
    WALKOUT = 12,
    DETAILS = 13,
    MANDATE = 14,
    REFEREE = 15,
    FEE = 16,
    COLLATERAL = 17,
    REACTIVATE = 18,
    STAFF = 19,
    OPERATINGEXPENSE = 20,
    STANDINGORDER = 21,
    SWEEP = 22,
    LODGE = 23,
    POSTPONE = 24,
    RETRN = 25,
    REPLACE = 26,
    RESCHEDULE = 27,
    COMPANY = 28,
    PAYMENT = 29,
    MMARKET = 30,
    PREPAYMENT = 31,
    INVOICEPAYMENT = 32,
    CONTRACT = 33,
    VARIATIONREQUISITION = 34,
    WORKCERTIFICATE = 35,
    PLACEMENTOVERRIDE = 36,
    TIEROVERRIDE = 37,
    MREVISION = 38,
    MCANCELLATION = 39,
    MPARTIALLIQUIDATION = 40,
    MCALLOPERATION = 41,
    MCOLLECTION = 42,
    MROLLOVER = 43,
    MMATURITY = 44,
    MPLACEMENT = 45,
    MLIQUIDATION = 46,
    REDISCOUNTING = 47,
    COUNTERPARTY = 48,
    CHEQUECLEARING = 49,
    CHEQUEREGISTRY = 50,
    BONDBUY = 51,
    BONDSELL = 52,
    CASH = 53,
    NOMINALACCOUNT = 54,
    CUSTOMER = 55,
    RISK = 56,
    LEGAL = 57,
    INTSUSPENSION = 58,
    JOURNAL = 59,
    Remittance = 60,
    DRAFT = 61,
    CHEQUEBOOK = 62,
    BANKSTATEMENT = 63,
    FUNDCHEQUE = 64,
    DISBURSEMENT = 65,
    RTGS = 66,
    DEALLETTER = 67,
    DEALSLIP = 68,
    DEALCERT = 69,
    LETTERS = 70,
    BIDDING = 71,
    CASAACCOUNT = 72,
    MCHEQUECLEARING = 73,
    MCHEQUEREGISTRY = 74,
    REPAYMENT = 75,
    CROLLOVER = 76,
    CTERMINATION = 77,
    CPARTIALLIQUIDATION = 78,
    CLIQUIDATION = 79,
    CDEPOSIT = 80,
    CCUSTOMER = 81,
    CANCELUNFUNDEDCHEQUE = 82,
    CANCELFUNDEDCHEQUE = 83,
    IBCUSTOMER = 84,
    MACCOUNTTRANSFER = 85,
    SALE = 86,
    PURCHASE = 87,
    OBBTakings = 88,
    OMO = 89,
    REPO = 90,
    REVERSEREPO = 91,
    BONDBIDDING = 92,
    TBBIDDING = 93,
    OVERDRAFT = 94,
    CUSTOMERSERVICEREQUEST = 95,
    SHARETRANSFERED = 96,
    PNCPND = 97,
    CREATEDEAL = 98,
    COT = 99,
    OBBPlacement = 100,
    SecuredTakings = 101,
    SecuredPlacement = 102,
    SecuredCall = 103,
    CASAREVERSAL = 104,
    REVERSEFREEZE = 105,
    ChangeAccount = 106,
    ChangeInRate = 107,
    Reversal = 108,
    PrincipalAddition = 109,
    PrincipalReduction = 110,
    DealInstruction = 111,
    TellersJournal = 112,
    FALSECHEQUECLEARING = 113,
    StopCheque = 114,
    ChequeRequest = 115,
    DefaultAccount = 116,
    SysconBackDateApproval = 117,
    AdjustSchedule = 118,
    UNFREEZE = 119,
    AccountSensitivity = 120,
    GeneralUpload = 121,
    AuditMemo = 122,
    DataUpload = 123,
    Refinance = 124,
    Validation = 125,
    ChangeRepaymentDate = 126,
    JournalReversal = 127,
    LOANREVERSAL = 128,
    TREASURYREVERSAL = 129,
    InfoWare = 130,
    Pension = 131,
    MileSoft = 132,
    BranchCreation = 133,
    DepartmentCreation = 134,
    MapDepartmentToBranch = 135,
    CreateCollateral = 136,
    CreateApprovingOfficer = 137,
    Tithe_And_Remittance = 138,
    STAMPDUTY = 139,
    LoanWriteOff = 140,
    ReviseInterestSuspension = 141,
    CREDITAUTHORIZATION = 142
            }
}
